### ISSUE TITLE
如何通过电脑直接下载到手机

### ISSUE THREAD

**Issue by jackqwc** [1299172402/everphotoDL#1]
作者您好，请问我想用手机连接电脑，直接下载到手机上，下载路径应该怎么填写呢？

例如我填写“此电脑/Redmi K50 Ultra/内部存储设备/01/everphoto”，可还是下载到电脑上

**Comment by 1299172402** [comment]
手机请使用官方APP下载，我这里本身就是不支持的

**Comment by 1299172402** [comment]
或者你可以使用Termux自行运行，这个在手机上也能用

**Comment by jackqwc** [comment]
好的，谢谢
