### ISSUE TITLE
图片整理一半就不继续整理

### ISSUE THREAD

**Issue by InspireLing** [1299172402/everphotoDL#4]
![image](https://github.com/1299172402/everphotoDL/assets/23207182/4aff830d-d3c8-47f2-9224-c512bcb8caa3)

无论是按照时间还是路径都卡一半，另外下载图片与本程序计算的不同、少了，但是再次下载也一下载到一些、还是剩余没下到的，一直无法下，希望可以弄出日志来哪张没下载到

**Comment by InspireLing** [comment]
> ![image](https://user-images.githubusercontent.com/23207182/275101570-4aff830d-d3c8-47f2-9224-c512bcb8caa3.png)
> 
> 无论是按照时间还是路径都卡一半，另外下载图片与本程序计算的不同、少了，但是再次下载也一下载到一些、还是剩余没下到的，一直无法下，希望可以弄出日志来哪张没下载到

不是操作问题、图片截图是终止了运行、实则enter后也是一样的

**Comment by 1299172402** [comment]
要看哪张没下载，可以在下载的时候，选择不显示跳过的文件，就只会输出新一次下载/失败的文件。有时候是因为同时下载数（线程数）太大等等原因导致网络阻塞，这些在同时下载数里调。


在整理中出现这样的问题，我这样也看不出来是为什么。不过你确定你没有手动停止他吗？因为我从截图里看到你有选择命令行，这时候命令行应该会被停止



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月14日(周六) 上午9:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [1299172402/everphotoDL] 图片整理一半就不继续整理 (Issue #4)




  

 
无论是按照时间还是路径都卡一半，另外下载图片与本程序计算的不同、少了，但是再次下载也一下载到一些、还是剩余没下到的，一直无法下，希望可以弄出日志来哪张没下载到
  
不是操作问题、图片截图是终止了运行、实则enter后也是一样的

**Comment by InspireLing** [comment]
> 要看哪张没下载，可以在下载的时候，选择不显示跳过的文件，就只会输出新一次下载/失败的文件。有时候是因为同时下载数（线程数）太大等等原因导致网络阻塞，这些在同时下载数里调。 在整理中出现这样的问题，我这样也看不出来是为什么。不过你确定你没有手动停止他吗？因为我从截图里看到你有选择命令行，这时候命令行应该会被停止
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年10月14日(周六) 上午9:32 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [1299172402/everphotoDL] 图片整理一半就不继续整理 (Issue #4) 无论是按照时间还是路径都卡一半，另外下载图片与本程序计算的不同、少了，但是再次下载也一下载到一些、还是剩余没下到的，一直无法下，希望可以弄出日志来哪张没下载到 不是操作问题、图片截图是终止了运行、实则enter后也是一样的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

我下载了源码弄了下、发现是整理是卡在os.rename这里 、 我把卡住的这些媒体自己改名移进去再运行 ，可以继续直到完成

**Comment by 1299172402** [comment]
OK，解决了就行
