### ISSUE TITLE
作者能打包一个mac的吗？

### ISSUE THREAD

**Issue by keventseng** [1299172402/everphotoDL#5]
RT.

**Comment by 1299172402** [comment]
macos自带环境，请自行从源代码运行


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月23日(周一) 下午3:39
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [1299172402/everphotoDL] 作者能打包一个mac的吗？ (Issue #5)




 
RT.
 
&mdash;
