### ISSUE TITLE
下载过程中卡住了怎么办

### ISSUE THREAD

**Issue by petermojiahua** [1299172402/everphotoDL#6]
如题，卡住不动了。关了重来可以接着下载吗？
![image](https://github.com/1299172402/everphotoDL/assets/44501811/489d9b35-f04e-4f7f-9a3b-2445d1ad79ad)

**Comment by 1299172402** [comment]
可以


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月13日(周一) 上午9:28
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [1299172402/everphotoDL] 下载过程中卡住了怎么办 (Issue #6)




 
如题，卡住不动了。关了重来可以接着下载吗？
 
 
&mdash;
