### ISSUE TITLE
感谢作者

### ISSUE THREAD

**Issue by PPG11** [1299172402/everphotoDL#8]
因为给我父母一直用的时光相册，但是我自己不用，今早我爸突然问我怎么这个相册不能用了，我查了一下才知道时光相册今晚就停止维护了。

第一时间打算自己写个脚本把照片都下载下来（但是苦命打工人只能晚上在做，有点担心晚上下载时间不够）。后来尝试在 GitHub 找一下，找到本 repo，非常非常感谢作者，赞助献上，爱您❤

**Comment by 1299172402** [comment]
Thanks~ *heart* *heart*
